import { FreshBox, Rental, ProductBatch } from './types';

export const INITIAL_BOXES: FreshBox[] = [
  {
    id: 'FB-101',
    type: 'S',
    location: 'warehouse',
    status: 'Available',
    batteryLevel: 98,
    currentTemp: 24.5,
    currentHumidity: 65,
    tempRange: '-2°C to 15°C',
    lastSanitized: '2026-06-23',
    pricePerDay: 75000,
  },
  {
    id: 'FB-102',
    type: 'M',
    location: 'truck',
    status: 'Active Rental',
    batteryLevel: 85,
    currentTemp: 11.2,
    currentHumidity: 88,
    tempRange: '-10°C to 20°C',
    lastSanitized: '2026-06-22',
    pricePerDay: 120000,
    assignedProductId: 'Fresh Tomatoes Batch A',
  },
  {
    id: 'FB-103',
    type: 'L',
    location: 'warehouse',
    status: 'Available',
    batteryLevel: 100,
    currentTemp: 22.0,
    currentHumidity: 60,
    tempRange: '-25°C to 25°C',
    lastSanitized: '2026-06-24',
    pricePerDay: 200000,
  },
  {
    id: 'FB-104',
    type: 'S',
    location: 'truck',
    status: 'Active Rental',
    batteryLevel: 74,
    currentTemp: 4.1,
    currentHumidity: 92,
    tempRange: '-2°C to 15°C',
    lastSanitized: '2026-06-21',
    pricePerDay: 75000,
    assignedProductId: 'Organic Spinach Batch B',
  },
  {
    id: 'FB-105',
    type: 'M',
    location: 'warehouse',
    status: 'Maintenance',
    batteryLevel: 12,
    currentTemp: 18.0,
    currentHumidity: 55,
    tempRange: '-10°C to 20°C',
    lastSanitized: '2026-06-15',
    pricePerDay: 120000,
  },
  {
    id: 'FB-106',
    type: 'L',
    location: 'truck',
    status: 'Available',
    batteryLevel: 95,
    currentTemp: 15.4,
    currentHumidity: 70,
    tempRange: '-25°C to 25°C',
    lastSanitized: '2026-06-23',
    pricePerDay: 200000,
  },
  {
    id: 'FB-107',
    type: 'M',
    location: 'truck',
    status: 'Available',
    batteryLevel: 90,
    currentTemp: 23.1,
    currentHumidity: 62,
    tempRange: '-10°C to 20°C',
    lastSanitized: '2026-06-24',
    pricePerDay: 120000,
  },
  {
    id: 'FB-108',
    type: 'S',
    location: 'warehouse',
    status: 'Available',
    batteryLevel: 88,
    currentTemp: 24.0,
    currentHumidity: 64,
    tempRange: '-2°C to 15°C',
    lastSanitized: '2026-06-22',
    pricePerDay: 75000,
  },
];

export const INITIAL_RENTALS: Rental[] = [
  {
    id: 'RNT-201',
    userName: 'IndoFresh Logistics',
    boxId: 'FB-102',
    startDate: '2026-06-24',
    endDate: '2026-06-29',
    usageMode: 'Distribution',
    pickupLocation: 'Brebes Agriculture Hub',
    destinationLocation: 'Jakarta Distribution Center',
    bookingDate: '2026-06-23',
  },
  {
    id: 'RNT-202',
    userName: 'SayurOrganik Corp',
    boxId: 'FB-104',
    startDate: '2026-06-23',
    endDate: '2026-06-27',
    usageMode: 'Storage + Distribution',
    pickupLocation: 'Lembang Farmhouse',
    destinationLocation: 'Bandung Premium Supermarket',
    bookingDate: '2026-06-22',
  },
];

export const INITIAL_PRODUCTS: ProductBatch[] = [
  {
    id: 'BAT-301',
    name: 'Fresh Tomatoes Batch A',
    category: 'Tomatoes',
    quantityKg: 350,
    origin: 'Brebes Agriculture Hub',
    destination: 'Jakarta Distribution Center',
    dateStored: '2026-06-24',
    expectedDeliveryDate: '2026-06-29',
    estimatedShelfLifeDays: 14,
    assignedBoxId: 'FB-102',
    qualityGrade: 'A',
    recommendation: {
      recommendedTemperature: '10–13°C',
      recommendedHumidity: '85–90% RH',
      airflowLevel: 'Medium',
      storageDurationLimit: '10–14 days',
      spoilageRisk: 'Low',
      handlingRecommendation: 'Do not store below 10°C to avoid chilling injury. Handle with care to prevent bruising.',
      energyOptimizationTip: 'Use eco-ventilation mode during early morning hours when ambient temperature is below 24°C.',
      reasoningSummary: 'Tomatoes are sensitive to chilling injuries and require moderate chilling and humidity to sustain ripening control.',
    },
  },
  {
    id: 'BAT-302',
    name: 'Organic Spinach Batch B',
    category: 'Leafy Vegetables',
    quantityKg: 150,
    origin: 'Lembang Farmhouse',
    destination: 'Bandung Premium Supermarket',
    dateStored: '2026-06-23',
    expectedDeliveryDate: '2026-06-27',
    estimatedShelfLifeDays: 7,
    assignedBoxId: 'FB-104',
    qualityGrade: 'A',
    recommendation: {
      recommendedTemperature: '0–5°C',
      recommendedHumidity: '90–95% RH',
      airflowLevel: 'High',
      storageDurationLimit: '5–7 days',
      spoilageRisk: 'Medium',
      handlingRecommendation: 'Pre-chill before loading. Keep humidity high to prevent wilting. Discard yellowed leaves before boxing.',
      energyOptimizationTip: 'Keep door seals tightly shut; high humidity requires continuous moderate fan operation to prevent condensation pooling.',
      reasoningSummary: 'Leafy vegetables have high respiration rates and moisture loss, necessitating high relative humidity and low temperature.',
    },
  },
];
